jobs:
  meow:
    requires: [~pr, ~commit]
    # sourcePaths: [README.md]
    image: node:8
    steps:
      - comment: |
          meta set meta.summary.coverage "Coverage increased by 15%"
          meta set meta.summary.markdown "this markdown comment is **bold** and *italic*"
      - status1: |
          meta set meta.status.findbugs "{\"status\":\"FAILURE\",\"message\":\"923 issues found. Previous count: 912 issues.\",\"url\":\"http://findbugs.com\"}"
      - status2: |
          meta set meta.status.coverage "{\"status\":\"SUCCESS\",\"message\":\"Coverage is above 80%.\"}"
