jobs:
  meow:
    requires: [~pr, ~commit]
    # sourcePaths: [README.md]
    image: node:8
    steps:
      - comment: |
          meta set meta.summary.coverage "Coverage increased by 15%"
          meta set meta.summary.markdown "this markdown comment is **bold** and *italic*"
