jobs:
  meow:
    settings:
      slack:
        channels:
          - 'slack-example'
          - 'screwdriver-cd:slack-test'
        statuses:
          - SUCCESS
          - FAILURE
    requires: [~pr, ~commit]
    image: node:8
    steps:
      - echo: echo hi
      - meta: meta set label VERSION_3.0
      - coverage: meta set tests.coverage 40.03234234
