jobs:
  meow:
    requires: [~pr, ~commit, ~sd@2897:main]
    # sourcePaths: [README.md]
    image: node:8
    steps:
      # - meow: sd-cmd exec sd/command@latest -d ./ -baseVersion "1.0"
      # - test: sd-cmd exec sd/git-tag-version@latest
      - echo: echo hi
      - meta: meta set label VERSION_3.0
